In [1]:
import kagglehub
path = kagglehub.dataset_download("muhammadshahidazeem/customer-churn-dataset")

e:\guvi project\churn dataser\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
!pip install pandas

Requirement already satisfied: pandas in .\env\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in .\env\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\env\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in .\env\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in .\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd 

customer_churn_dataset=pd.read_csv("customer_churn_dataset-training-master.csv")

In [4]:
customer_churn_dataset

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.00,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.00,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.00,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.00,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.00,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
440828,449995.0,42.0,Male,54.0,15.0,1.0,3.0,Premium,Annual,716.38,8.0,0.0
440829,449996.0,25.0,Female,8.0,13.0,1.0,20.0,Premium,Annual,745.38,2.0,0.0
440830,449997.0,26.0,Male,35.0,27.0,1.0,5.0,Standard,Quarterly,977.31,9.0,0.0
440831,449998.0,28.0,Male,55.0,14.0,2.0,0.0,Standard,Quarterly,602.55,2.0,0.0
440832,449999.0,31.0,Male,48.0,20.0,1.0,14.0,Premium,Quarterly,567.77,21.0,0.0

In [5]:
customer_churn_dataset=customer_churn_dataset.drop_duplicates(subset=["CustomerID"])
customer_churn_dataset=customer_churn_dataset.dropna()

In [6]:
customer_churn_dataset=customer_churn_dataset.drop(columns="CustomerID")

In [7]:
from sklearn.preprocessing import LabelEncoder
lb_gender=LabelEncoder()
lb_subsribtion=LabelEncoder()
lb_Contract=LabelEncoder()

In [36]:
a

array([0, 1])

In [8]:
customer_churn_dataset["Gender"]=lb_gender.fit(customer_churn_dataset["Gender"])
customer_churn_dataset["Subscription Type"]=lb_subsribtion.fit(customer_churn_dataset["Subscription Type"])
customer_churn_dataset["Contract Length"]=lb_Contract.fit(customer_churn_dataset["Contract Length"])
customer_churn_dataset["Gender"]=lb_gender.transform(customer_churn_dataset["Gender"])
customer_churn_dataset["Subscription Type"]=lb_subsribtion.transform(customer_churn_dataset["Subscription Type"])
customer_churn_dataset["Contract Length"]=lb_Contract.transform(customer_churn_dataset["Contract Length"])

In [9]:
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()

In [10]:
title=customer_churn_dataset.columns

In [11]:
with open("column name.txt","w")as name:
    for i in title :
        name.writelines(f"{i}\n")

In [12]:
customer_churn_dataset=Ms.fit(customer_churn_dataset)
customer_churn_dataset=Ms.transform(customer_churn_dataset)

In [13]:
customer_churn_dataset=pd.DataFrame(customer_churn_dataset,columns=title)

In [14]:
customer_churn_dataset

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,0.255319,0.0,0.644068,0.448276,0.5,0.600000,1.0,0.0,0.924444,0.551724,1.0
1,1.000000,0.0,0.813559,0.000000,1.0,0.266667,0.0,0.5,0.507778,0.172414,1.0
2,0.787234,0.0,0.220339,0.103448,0.6,0.600000,0.0,1.0,0.094444,0.068966,1.0
3,0.851064,1.0,0.627119,0.689655,0.7,0.233333,1.0,0.5,0.328889,0.965517,1.0
4,0.106383,1.0,0.525424,0.655172,0.5,0.266667,0.0,0.5,0.574444,0.655172,1.0
...,...,...,...,...,...,...,...,...,...,...,...
440827,0.510638,1.0,0.898305,0.482759,0.1,0.100000,0.5,0.0,0.684867,0.241379,0.0
440828,0.148936,0.0,0.118644,0.413793,0.1,0.666667,0.5,0.0,0.717089,0.034483,0.0
440829,0.170213,1.0,0.576271,0.896552,0.1,0.166667,1.0,1.0,0.974789,0.275862,0.0
440830,0.212766,1.0,0.915254,0.448276,0.2,0.000000,1.0,1.0,0.558389,0.034483,0.0
440831,0.276596,1.0,0.796610,0.655172,0.1,0.466667,0.5,1.0,0.519744,0.689655,0.0

In [15]:
import pickle

In [16]:
with open("mdel.pkl","wb") as f:
    pickle.dump(customer_churn_dataset,f)

In [17]:
with open("LabelEncoder_g.pkl","wb") as f:
    pickle.dump(lb_gender,f)
with open("LabelEncoder_s.pkl","wb") as f:
    pickle.dump(lb_subsribtion,f)
with open("LabelEncoder_c.pkl","wb") as f:
    pickle.dump(lb_Contract,f)

In [18]:
with open('Minmaxsacler.pkl',"wb") as f:
    pickle.dump(Ms,f)

In [19]:
with open("column name.txt")as f:
    h=f.readlines()

In [20]:
h

['Age\n',
 'Gender\n',
 'Tenure\n',
 'Usage Frequency\n',
 'Support Calls\n',
 'Payment Delay\n',
 'Subscription Type\n',
 'Contract Length\n',
 'Total Spend\n',
 'Last Interaction\n',
 'Churn\n']

In [21]:
import re
h=[i.strip() for i in h]

In [22]:
h

['Age',
 'Gender',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Subscription Type',
 'Contract Length',
 'Total Spend',
 'Last Interaction',
 'Churn']